### ISSUE TITLE
Process PDF Files

### ISSUE THREAD

**Issue by LWaetzig** [LWaetzig/StudentChatbot#1]
## Description
Create worflow that a passed pdf file can be processed and the text or images are extracted

## Key Features
- [ ] PDF file can be read
- [ ] Text can be extracted
- [ ] Images and texts can be distinguished
- [ ] text is splitted into chunks
- [ ] embeddings are extracted

**Comment by lanteanair** [comment]
problems with PDF files: 
- no inherent structure
- structure based extraction (i.e. PyPDF et. al) doesnt retain document structure
- solution could be OCR
- building custom pytesseract model
- maybe different preproc approaches for different documents
- "clean documents" -> remove recurring headers / footnotes
- how to deal with images?

**Comment by lanteanair** [comment]
first appraoch by Lars:
- structure based PDF extraction (PyPDF2)
- OCR to extract image text

problems / possible improvements:
- use OCR also for text / structure extraction -> can pick up tables, maybe filter recurring elements like headers (cleaner dataset)
- if RAG is used, maybe save images in db?

what does the further use look like? 
idea for the fileupload chatbot - RAG based Chat interaction: 
- user uploads file
- file gets processed (PDF extraction, chunking, saved to db)
- user asks a question
- semantic search equivalent looks for best fitting chunk in database
- found chunk + question get passed on to the LLM
- website returns the LLM output

**Comment by LWaetzig** [comment]
Propose the following workflow to process pdf files and use them in our application:
![Process](https://github.com/LWaetzig/StudentChatbot/assets/92372282/42eba414-1f4a-4fcf-8d33-2c2734d00475)
