### ISSUE TITLE
Research Model availablilty

### ISSUE THREAD

**Issue by LWaetzig** [LWaetzig/StudentChatbot#13]
## Objective
Research how to access llm (using huggingfaceAPI or download model to run it locally)

## Key features
- [x] both methods are tested
- [ ] best method is documented and used

**Comment by adse18** [comment]
Using language model via API calls is obviously much simpler but less precise -> is currently implemented as a MVP
Finetuning is the best method to fulfill our objectives, probably a we need to finetune a german language model on summarization for the best results - prototype could be an english summarization model

The scope and target of the finetuning has to be discussed and can afterwards be tackled & implemented
