### ISSUE TITLE
Create GUI to interact

### ISSUE THREAD

**Issue by alexx1374** [LWaetzig/StudentChatbot#3]
## Description
Create a nice GUI, so that the user can interact with our Chatbot

## Key Features
- [x] possibility to pass text
- [x] file upload

**Comment by LWaetzig** [comment]
Update: UI with basic features is implemented

![image](https://github.com/LWaetzig/StudentChatbot/assets/92372282/786be901-7f47-4003-b737-0678ecb6ddea)
